---
driver:
  name: vagrant
  vm_hostname: www.nektos.com
  require_chef_omnibus: 12.5.1

provisioner:
  name: chef_zero
  environments_path: "test/environments"

platforms:
  - name: centos-6.7
    driver_config:
      network:
        - ["forwarded_port", {guest: 8080, host: 8000}]
      customize:
        memory: 1024
        cpuexecutioncap: 50

busser:
  sudo: false

suites:
  - name: default
    run_list:
      - recipe[aftp::default]


