---
driver:
  name: vagrant
  vm_hostname: www.nektos.com
  require_chef_omnibus: 12.5.1

provisioner:
  name: chef_zero
  environments_path: "test/environments"

platforms:
  - name: centos-6.7
    driver_config:
      customize:
        memory: 1024
        cpuexecutioncap: 50

suites:
  - name: default
    run_list:
      - recipe[aftp::default]
    attributes:
      aftp:
        git_repo: "cplee/aftp"
        git_commit: "master"


